# Generated by Django 6.1 on 2026-08-10 17:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_inscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student_comment', models.TextField(blank=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('a_tiempo', 'A tiempo'), ('tardia', 'Tardía')], default='a_tiempo', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'db_table': 'entrega',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tareas.entrega')),
            ],
            options={
                'verbose_name': 'archivo_entrega',
                'verbose_name_plural': 'archivo_entregas',
                'db_table': 'archivo_entrega',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('max_score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'db_table': 'tarea',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_entrega_tarea_estudiante'),
        ),
    ]
