# Generated by Django 6.1 on 2026-08-09 16:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'db_table': 'material',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo_materials', to='contenidos.material')),
            ],
            options={
                'verbose_name': 'archivo_material',
                'verbose_name_plural': 'archivo_materiales',
                'db_table': 'archivo_material',
            },
        ),
    ]
